{
 "title": "Metic Monitoring",
 "tags": [ "linux" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataCenter", "label": "DataCenter", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(job)" } },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({job=\"$cluster\"},exported_instance)"
    }
   },
   {
    "name": "node_gpu",
    "label": "node_gpu",
    "query": {
     "query": "label_values({job=\"$cluster\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Center Resource Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(Cluster_Total_CPU_Count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_load_average_1m) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Data Center GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(Cluster_Node_Total_GPU_Power_Usage)",
     "legendFormat": "{{DataCenter}}"
    }
   ]
  },
  {
   "title": "Data Center Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(Network_Traffic_Basic1)", "legendFormat": "{{label_name}}" },
    { "expr": "- sum(Network_Traffic_Basic2)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cluster Resource Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cluster_Total_CPU_Core_Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_Total_CPU_Count{job=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Cluster_Node_CPU_Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "Cluster_Node_CPU_Usage", "legendFormat": "{{exported_instance}}" }
   ]
  },
  {
   "title": "Cluster_Avg_CPU_Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "Cluster_Avg_CPU_Usage{job=\"$cluster\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_Avg_System_Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "Cluster_Node_Avg_System_Load{job=\"$cluster\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_GPU_Type_Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Cluster_Node_GPU_Type_Number) by(modelName)",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_Avg_GPU_Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "Cluster_Node_Avg_GPU_Usage{job=\"$cluster\"}",
     "legendFormat": "{{job}} {{modelName}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_Total_GPU_Power_Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "Cluster_Node_Total_GPU_Power_Usage{job=\"$cluster\"}",
     "legendFormat": "{{exported_instance}} {{modelName}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_Avg_GPU_Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "Cluster_Node_Avg_GPU_Temperature{job=\"$cluster\"}",
     "legendFormat": "{{exported_instance}} {{modelName}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_Total_Disk_Avail_Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_Node_Total_Disk_Avail_Bytes {job=\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster_Total_Mem_Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Cluster_Total_Mem_Free{job=\"$cluster\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_Mem_Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "Cluster_Node_Mem_Free{job=\"$cluster\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Cluster_Node_Total_Packet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "Cluster_Node_Total_Packet_Receive{job=\"$cluster\"}",
     "legendFormat": "{{exported_instance}} Receive"
    },
    {
     "expr": "- Cluster_Node_Total_Packet_Transmit{job=\"$cluster\"}",
     "legendFormat": "{{exported_instance}} Transmit"
    }
   ]
  },
  {
   "title": "Node Resource Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_pressure_cpu_waiting_seconds_total_5m{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "node_pressure_memory_waiting_seconds_total_5m{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "Mem"
    },
    {
     "expr": "node_pressure_io_memory_waiting_seconds_total_5m{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_busy_5m{job=\"$cluster\", exported_instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{job=\"$cluster\", exported_instance=\"$node\"}) * 100 / count(count(node_cpu_seconds_total{job=\"$cluster\", exported_instance=\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$cluster\", exported_instance=\"$node\"} / node_memory_MemTotal_bytes{job=\"$cluster\", exported_instance=\"$node\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_byte{job=\"$cluster\", exported_instance=\"$node\"} - node_memory_SwapFree_bytes{job=\"$cluster\", exported_instance=\"$node\"}) /0.001 + (node_memory_SwapTotal_byte{job=\"$cluster\", exported_instance=\"$node\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"$cluster\", exported_instance=\"$node\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"$cluster\", exported_instance=\"$node\"} - node_boot_time_seconds{job=\"$cluster\", exported_instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_byte{job=\"$cluster\", exported_instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$cluster\", exported_instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "CPU_Basic1{job=\"$cluster\",  exported_instance=\"$node\"}",
     "legendFormat": "Busy System"
    },
    {
     "expr": "CPU_Basic2{job=\"$cluster\",  exported_instance=\"$node\"}",
     "legendFormat": "Busy User"
    },
    {
     "expr": "CPU_Basic3{job=\"$cluster\",  exported_instance=\"$node\"}",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "CPU_Basic5{job=\"$cluster\",  exported_instance=\"$node\"}",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "CPU_Basic6{job=\"$cluster\",  exported_instance=\"$node\"}",
     "legendFormat": "Busy Other"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$cluster\", exported_instance=\"$node\"} - node_memory_MemFree_bytes{job=\"$cluster\", exported_instance=\"$node\"} - (node_memory_Cached_bytes{job=\"$cluster\", exported_instance=\"$node\"} + node_memory_Buffers_bytes{job=\"$cluster\", exported_instance=\"$node\"} + node_memory_SReclaimable_bytes{job=\"$cluster\", exported_instance=\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$cluster\", exported_instance=\"$node\"} + node_memory_Buffers_bytes{job=\"$cluster\", exported_instance=\"$node\"} + node_memory_SReclaimable_bytes{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"$cluster\", exported_instance=\"$node\"} - node_memory_SwapFree_bytes{job=\"$cluster\", exported_instance=\"$node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "Network_Traffic_Basic1{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "Network_Traffic_Basic2{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$cluster\", exported_instance=\"$node\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"$cluster\", exported_instance=\"$node\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(DCGM_FI_DEV_GPU_TEMP)" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{exported_instance=\"$node_gpu\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_instance=\"$node_gpu\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{exported_instance=\"$node_gpu\"}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{exported_instance=\"$node_gpu\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 70 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{exported_instance=\"$node_gpu\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{exported_instance=\"$node_gpu\"} * 1000000",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{exported_instance = \"$node_gpu\"}"
    }
   ]
  },
  {
   "title": "Processes Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_blocked{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{job=\"$cluster\", exported_instance=\"$node\"}",
     "legendFormat": "Processes in runnable state"
    }
   ]
  }
 ]
}